### PR TITLE
Un-pin Pydantic

### PR DESCRIPTION
**Pull request by SimonBoothroyd**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SimonBoothroyd** [comment]
@mattwthompson I think 0.3.0 has the try / catch to handle v1 and v2 right?

**Comment by SimonBoothroyd** [comment]
@conda-forge-admin, please rerender

**Comment by j-wags** [comment]
Checking pydantic 2 compatibility here https://github.com/openforcefield/openff-bespokefit/pull/357

**Comment by j-wags** [comment]
The compatibility checks above raise a bunch of errors, even when trying a range of versions of OpenFF ecosystem packages. So I don't think this is ready for release.

**Comment by mattwthompson** [comment]
This should work in 0.3.0, yeah: https://github.com/openforcefield/openff-bespokefit/commit/3611f36e9f67ab31fbccdaef73d89be0659c979f

**Comment by j-wags** [comment]
@mattwthompson - It's possible I'm overlooking something, but bespokefit CI fails if I bring in [pydantic 2](https://github.com/openforcefield/openff-bespokefit/actions/runs/10778769798/job/29890842737?pr=357). Could you clarify?

**Comment by mattwthompson** [comment]
Something unexpected is going on: https://github.com/openforcefield/openff-bespokefit/pull/358

**Pull request closed without merging**
