### PR TITLE
0.3.0 build 0

### PR DESCRIPTION
**Pull request by j-wags**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by j-wags** [comment]
@conda-forge-admin, please rerender

**Review by j-wags — COMMENTED** [review]
rethink qcelemental/engine/portal version constraints

**Review by mattwthompson — APPROVED** [review]
LGTM, two things that I thought about but don't justify changing

* Many dependencies aren't imported directly and are brought in by other dependencies so could be viewed as redundant here. But there isn't much wrong with double-listing them and it's arguably better to have more than fewer
* If there are future changes to any of these upstreams that might break things, now is a good time to safeguard against them. But I don't think any not listed with upper constraints (toolkit, QC*,  any of the LPW or FastAPI-related tools) are likely to change soon

**Comment by j-wags** [comment]
Thanks. The upper constraint idea in particular is really interesting (and I was just reading about the `~=` specification in conda requirements which could be relevant here). I won't put that in this PR but it could be a good call for future ease-of-maintenance if we do it consistently.

**Pull request merged**
