### PR TITLE
0.4.1 build 0

### PR DESCRIPTION
**Pull request by j-wags**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by j-wags** [comment]
@conda-forge-admin, please rerender

**Comment by mattwthompson** [comment]
FYI (since we may do this in all of our repos) the linter complaints can be resolved by
* Adding boilerplate that looks like this, in order to follow CFEP-26: https://github.com/conda-forge/openff-units-feedstock/pull/21/commits/1dfd97360cb7b122261fd2fe62c14317506eb425
* Working around a `conda-build` bug if we're not following their default minimum (I think it 3.9 still) https://github.com/conda-forge/openff-units-feedstock/pull/21/commits/c84e2258bc7f083c2e4afdb84a334063d307bf4c

And then re-rendering

**Comment by j-wags** [comment]
Thanks for the tip. Kinda promising that C-F is looking to standardize python support windows, but looking into it they don't have a firm timetable/process for deciding what the minimum version is yet. Once they do we could consider adopting their schedule and just using their `python_min`. But in the meantime I'd rather have the rerendering bot yell at me than have our python version out of sight in a separate file.

**Comment by mattwthompson** [comment]
Their linter might have changed in the past day or two - previously I was forced to use `{{ python_min }}` even when it matches the global pinning default (currently 3.9). I wouldn't have bothered with the extra config if I didn't have to ... shrugs. If it works, it works.

https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/af28e9fa6211aa96feb9abd01c4c4cfcf8161175/recipe/conda_build_config.yaml#L796-L799

**Comment by j-wags** [comment]
Ooh, fun new build error

```
    openff-toolkit:            0.9.0-pyh44b312d_0                     conda-forge
    openff-toolkit-base:       0.16.5-pyhd8ed1ab_0                    conda-forge
```

Cool. Cool cool cool.

**Comment by mattwthompson** [comment]
That's ... surprising, to say the least

**Comment by mattwthompson** [comment]
Maybe?

```yaml
    run_constrained:
      ...
      - openff-toolkit >=0.16
```

**Pull request merged**
