### PR TITLE
0.4.0 build 0

### PR DESCRIPTION
**Pull request by j-wags**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by j-wags** [comment]
@conda-forge-admin, please rerender

**Review by jthorton — APPROVED** [review]
Thanks @j-wags !

**Comment by j-wags** [comment]
Just realized we have a pin in testing that we don't have in the Conda package. Testing it now but boarding an airplane 

https://github.com/openforcefield/openff-bespokefit/pull/360

I'll do what I can from Wi-Fi but otherwise I'll be at work on Monday. Feel free to cut the release if you're up to monitor it and patch the package if anything goes wrong.

**Comment by j-wags** [comment]
Ok, I'd give this a green-ish light for merge - only uncertainty is why https://github.com/openforcefield/openff-bespokefit/pull/360 is pulling in QPortal 0.54.1 instead of 0.56, but... :shrug: the tests ARE passing. 

@jthorton  If you're up to monitor this post-release, feel free to merge. Otherwise I'll move it forward when I'm back to work in California on Monday.

**Comment by jthorton** [comment]
Yeah strange that the 3.11 tests are using 0.54.1 and the 3.10 are using 0.56 but they are all passing so this should be fine. Lets go for it!

**Pull request merged**
