### PR TITLE
Require `h5py >=3.6`

### PR DESCRIPTION
**Pull request by mattwthompson**
This implements my proposed solution to some deployment issues

https://github.com/openforcefield/openff-bespokefit/issues/227#issuecomment-1414107984

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mattwthompson** [comment]
@conda-forge-admin, please rerender

**Review by jthorton — APPROVED** [review]
Great catch!

**Comment by mattwthompson** [comment]
IIUC it's not straightforward to test that Psi4 works from inside the build recipe? Since this recipe doesn't build anything with Psi4 in it, we'd have to bring it in and do something that starts a QC calculation without waiting it to finish, or maybe just imports Psi4's Python stuff? I'm pretty sure the current test doesn't catch this case

https://github.com/conda-forge/openff-bespokefit-feedstock/blob/98f0202659bae04bd0638018dff79c9cffb700c0/recipe/meta.yaml#L55-L58

I'm pretty sure I was able to import the Python package in the "broken" environment that had an older h5py in it. Maybe an h5py import in this block would help? I'll raise an issue about this since it's not getting fixed here.

**Review by j-wags — APPROVED** [review]
Looks great. I commented on the other issue as well.

**Pull request merged**
